### PR TITLE
No more zcml in core

### PR DESCRIPTION
**Pull request by vangheem**
@bloodbare this is the last of our zcml.

Since this touches more components and completely removes zcml, I'll wait for you to merge this one.

### CODE REVIEW

**Comment by miohtama** [comment]
koala

**Comment by datakurre** [comment]
If we'd knew all this year ago, we'd probably built this on top of pyramid. Oh, the irony. (We choosed ZTK for familiarity and Dexterity compatibility and. Oath reasons are gone now :)

**Comment by vangheem** [comment]
We didn't choose the ztk bits because of zcml... pyramid still isn't async.

**Comment by datakurre** [comment]
Agreed on ZCML. And we did start without it. We just needed to add it back very soon, because learning something else would have slowed down the sprint.

Pyramid is not async as such, but we maybe could have used its configuration and security, possibly even traverse. All of being simpler that zope-counterparts. Sure there would have been surprises because of its WSGI design (and how to make it work with asyncio based http server).

Btw, how do configuration conflicts look with the new configuration? In venusianconfiguration I had to explicitly provide "ParserInfo" for zope.configuration context to get configuration conflict errors to show the exact code lines with conflict.

**Comment by vangheem** [comment]
I haven't dealt with configuration conflicts yet so I'm not quite sure what happens right now :(

**Pull request merged**
