### PR TITLE
WIP: replace zcml with hjson

### PR DESCRIPTION
**Pull request by vangheem**
@bloodbare what do you think of this?

I think the only thing we gain from getting rid of ZCML is that it's one less thing for people to learn.

The syntax is a bit more compact, easier to edit. People know JSON...

If we like this approach, or something like it, I can convert all zcml to json.

### CODE REVIEW

**Comment by thet** [comment]
I liked what i saw on the HJSON website and it's a nice approach, but actually HJSON != JSON. It's a different syntax. So people have actually again learn something else. Plus, lots of brackets and braces ``[{}]``.
In my opinion the HJSON configuration is harder to read than ZCML.

Also, the problem with ZCML is not that it's XML, it's more the configuration subject and the concepts behind it. The HJSON approach does not solve this problem. You'll still have to configure adapters and utilities, include packages and so forth.

Why not configuring all in code, like in Pyramid? You will need the venusian approach of scanning the project in order to be able to configure it (which I actually dislike because of lack of excitability, but so be it). @datakurre once experimented with an approach of removing the need of ZCML in favor of the Pyramid way of having configuration decorators in Python code.

**Comment by vangheem** [comment]
> but actually HJSON != JSON

Yes, that's the point. JSON doesn't provide a way to do comments :) HJSON will still parse regular json so we don't have to use all the features. In any case, it's just an example. We could go with something else entirely...

> Plus, lots of brackets and braces [{}].

Yes, I'm not sure about this either. XML is verbose in other ways though.

> In my opinion the HJSON configuration is harder to read than ZCML

I wondered that at first as well; however, I wonder if it's because we've been reading zcml for years. What your standard web developer would say if presented with the 2.

> Also, the problem with ZCML is not that it's XML

I think it's part of the problem.

> Why not configuring all in code, like in Pyramid

I'm not sure... Pyramid doesn't actually use very much ZCA anymore so maybe it's not a great comparison. From what I've seen in the experiments with replacing ZCML with python code is that it looked pretty nasty as well.

Let's take us back a moment. Right now in `plone.server` we use json to configure various parts of it. We also use json to define our API endpoints. A user of `plone.server` will only encounter zcml if they write an addon. Since `plone.server` introduced the new json configuration, it seemed appropriate to try and get rid of the ZCML approach. The advantage is that it's one less thing for a new-comer to have to know about. Yes, they still need to know about adapters, subscribers, etc; however, there isn't another configuration syntax.

Also, I thought we needed comments in our json configuration.

**Comment by jaroel** [comment]
hjson, yet another thing to learn. ;)

If you're new to programming the first thing you'll ask is "why can I comment in half the .json files, but not in others". Consistency is key is just a important as easy of use.

Personally I don't get why you wouldn't just go with a python config.py or setting.py. It has comments and dictionary style that is close enough to json.
Plus, people will have to learn Python in the first place, or already have.

**Comment by fredvd** [comment]
IMHO the underlying problem is the steep learning curve of the component architecture, which is a very powerful system but also inherently complex. It took me years to understand most of the implications and how it enables all sort of things.

It was very unfortunate that the planned ZCA training for PloneConf 2016 was canceled due to limited time. That would have given us more insight on teaching it and basic material to expand the documentation. 

There quite a bit of documentation In the package documentation, some papers on the ZCA, but there's not a visible pragmatic introduction tailored to Plone and intermediate developers/integrators. It's the curse of knowledge, once you get it, you don't understand anymore what's so difficult about it :-P

Different notations will sure impact readability and adoption for some, but it will introduce yet another configurattion language that will take years and years in the community to absorb and replace the xml format, if it ever will.

**Comment by bloodbare** [comment]
There is two issues:

* zcml on json : I really would not change that right now, zcml is close to ZCA and its for low level development

* config.json : The entry configuration for the plone.server, its great that is json because its normally generated throw external docker entrypoint scripts. For the use case of having comments, I'm not against of using hjson but adding a dependency just for reading the initial json its too much and if its automatic generated does not have lot of sense to need comments.

* api.json : I'm agree that on api.json there is the need for comments, but as we are building a api.json to html documentation it would be great that comments are also as fields on the api.json (like there is an example at : https://github.com/plone/plone.server/blob/master/src/plone.server/plone/server/api/api.json#L26 )

So I don't see the need.

**Comment by vangheem** [comment]
zcml on json: I agree

config.json: Maybe it's just bothering me more than it should. npm and others use plain json just fine for configuration. Just provide docs elsewhere I guess.

api.json: I agree, since this is structured well enough, we should be able to embed comments.

Alright, I'll leave the branch around if we ever want to revisit something like this. For me at least, it was worth the exploration.

I'm still not happy with our mix of json/zcml... so let's keep thinking about it long term...

**Comment by smcmahon** [comment]
This has nothing to do with the merits of this particular pull request, but if we're looking for a more readable form of JSON, why wouldn't we use YAML? It's a JSON superset that's well-documented, well-supported, and rigorously defined.

**Comment by datakurre** [comment]
I've used my generic Python syntax for ZCA for a few years for now with very little issues. https://pypi.python.org/pypi/venusianconfiguration Here's an example with crazy amount of registrations https://github.com/datakurre/collective.atrfc822/blob/master/src/collective/atrfc822/fields.py

**Comment by vangheem** [comment]
Over all these years, we still can't quite shake zcml.

I'm not sure what this says about ZCML. Maybe it's not as bad as we think it is or maybe it's so complicated that it's difficult to replace well.

For plone.server, I'd like to explore some way of replacement. Following the route pyramid has taken over the years seems to be the most sensible solution. We don't need to re-solve all the problems they have solved.

**Comment by datakurre** [comment]
Well, let's think why grok failed. It didn't only include "new syntax", but also new conventions over configuration, and it required a reimplementation of all directives as grok directives / classes (it tried to replace whole zope.configuration, not just zcml). So, you could never use from without ZCML.

Venusianconfiguration (yes, it uses Venusian from Pyramid) does not implement any directives, but only maps Python code to zope.configuration directives. (And, of course, it also need to patch zcml include to check for "configuration.py" to be backwards compatible.)

**Comment by datakurre** [comment]
(So, with Venusian, we do have a lot of in-house packages without any ZCML.)

**Pull request closed without merging**
