### PR TITLE
Move participation to after traversal

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by bloodbare** [comment]
One of the ideeas I had about participation is that can have multiple participations, so it may be that there is more than credentials running at the same time and allowing different users. That's why the root was on the root.

What opinion do you have on this idea ?

**Comment by vangheem** [comment]
That seems fine. I'll add back in the root by default. However, I'd still like to move it all after traversal. Is that okay?

**Comment by bloodbare** [comment]
Its great, can we move it to before translator adapter ? translator may need user there.

**Comment by vangheem** [comment]
k, done and added changelog.

**Pull request merged**
