### PR TITLE
fix fallback cors check

### PR DESCRIPTION
**Pull request by vangheem**
@bloodbare notice I also added default cors settings here of everything to be open. It seems to me that this is a fine default setting with the assumption when you deploy you hone it in.

The big change to review here is traversal.py changes--I don't think that check is valid anymore but I would like if you made sure that I'm correct.

### CODE REVIEW

**Comment by bloodbare** [comment]
Sorry I missed this pull request, its great!

**Comment by davisagli** [comment]
I'd encourage not making it open by default. If it's restricted than people will be forced to think about their settings. If it's open they'll just forget, and it'll be less secure.

**Comment by bloodbare** [comment]
I like the idea : https://github.com/plone/plone.server/commit/482e405799c60cdf5a7b947323eec2708b04f49b

**Comment by vangheem** [comment]
Even better +1

**Pull request merged**
